# For more information: https://laravel.com/docs/sail

x-db-common-values:
    db-name: &db-name '${DB_DATABASE}'
    db-user: &db-user '${DB_USERNAME}'
    db-pass: &db-pass '${DB_PASSWORD}'

services:
    app:
        container_name: ${COMPOSE_PROJECT_NAME}
        build:
            context: ./docker/${DOCKER_PHP_VERSION:-8.2}
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-${DOCKER_PHP_VERSION:-8.2}/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/package'
            - './exampleApp:/var/www/html'
        networks:
            - internal
            - shared
        depends_on:
            - mysql_testing
    mysql_testing:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_DATABASE: *db-name
            MYSQL_USER: *db-user
            MYSQL_PASSWORD: *db-pass
            MYSQL_ROOT_PASSWORD: *db-pass
            MYSQL_ROOT_HOST: "%"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - internal
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    postgres_testing:
        image: 'postgres:17'
        environment:
            POSTGRES_DB: *db-name
            POSTGRES_USER: *db-user
            POSTGRES_PASSWORD: *db-pass
            POSTGRES_HOST_AUTH_METHOD: 'trust'
        networks:
            - internal
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            retries: 3
            timeout: 5s
networks:
    internal:
        internal: true
    shared:
        external: true
